# fly.toml app configuration file generated for young-feather-4191 on 2023-09-15T20:30:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-feather-4191"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
